### ISSUE TITLE
pip install dataduct is failing due to environment error: mysql_config not found

### ISSUE THREAD

**Issue by vyasmanish** [coursera/dataduct#261]
```
Collecting dataduct
  Downloading dataduct-0.4.0.tar.gz (74kB)
    100% |████████████████████████████████| 81kB 134kB/s
Requirement already satisfied: boto>=2.38 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from dataduct)
Collecting MySQL-python>=1.2.3 (from dataduct)
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 16kB/s
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-tR_esf/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
```

**Comment by adamgotterer** [comment]
I'm also having the same issue

**Comment by adamgotterer** [comment]
Fixed by installing mysql

**Comment by arielvalentin** [comment]
Sorry, why do we have to install MySQL? Is there a version that we can install that omits this dependency?

**Comment by emonkey** [comment]
> Fixed by installing mysql

You don't need the full server, only `sudo apt-get install libmysqlclient-dev`
